### ISSUE TITLE
日期顯示問題

### ISSUE THREAD

**Issue by ashley0821** [melodiehsu/vue-roc-date-picker#3]
您好，非常感謝您製作了這個民國年選擇器，這個日期選擇器設計得非常好看，但是我在使用過程中發現了一個讓我感到疑惑的地方，所以冒昧請問您一個問題:

首先我把日期選擇器綁定startDate這個值
![image](https://github.com/melodiehsu/vue-roc-date-picker/assets/86181714/64e7378d-733d-436c-9ed1-4a62af0502e8)

接著賦值給startDate
![image](https://github.com/melodiehsu/vue-roc-date-picker/assets/86181714/44e39cce-aa8f-41be-83e4-07a7ad712029)

透過主控台確認startDate的值是正確的 型別也是string
![image](https://github.com/melodiehsu/vue-roc-date-picker/assets/86181714/6cd3c7b8-607a-4485-acd2-bb61a9421fd6)

但是我的畫面卻無法顯示出該日期
![image](https://github.com/melodiehsu/vue-roc-date-picker/assets/86181714/e1a3a7f1-bf2c-4ade-8bf2-67bed3d07706)

想請教您為什麼會這樣? 是不是我操作有誤? 謝謝

**Comment by melodiehsu** [comment]
i will check and get back to you soon!

**Comment by melodiehsu** [comment]
抱歉這麼晚回覆。
當初設計時沒考慮到直接將值塞進 modelValue 中的情況，所以如果是想要讓日期直接顯示在 input 中可以使用 prop: default-value。
```
<ROCDatePicker
  v-model="selectedDate"
  :default-value="defaultDate"
/>
```

**Comment by melodiehsu** [comment]
已更新版本 0.1.3，可以升版修正此問題 :)
